### ISSUE TITLE
Add Image at Tutorial, Login, Join View

### ISSUE THREAD

**Issue by BaekJinCho** [BaekJinCho/HaruApp#6]
- Navigation item에 들어가는 이미지 사이즈가 너무 커 이미지 수정 작업 필요.

**Comment by projectlife724** [comment]
네비게이션 아이템에서 구체적으로 어떤 이미지인지?

**Comment by BaekJinCho** [comment]
Arrow, Pencil Image 크기가 불규칙

**Comment by projectlife724** [comment]
arrow와 pencil image 크기는 사실 같음 
다만, pencil의 모양 때문에 작게 보이는듯함.
일단 조금 사이즈를 늘려서 asset에 추가하겠음.

**Comment by projectlife724** [comment]
pencil icon 1.5pt 늘려서 asset 에 추가
keyboard toolbar용 camera 및 library icon도 추가하였음
icon은 Detail Page에 위치

**Comment by BaekJinCho** [comment]
수정해서 올린 Image로 바꾸는 작업 완료
