### ISSUE TITLE
Make a MainView Page

### ISSUE THREAD

**Issue by BaekJinCho** [BaekJinCho/HaruApp#7]
- 일기를 작성 후 수정화면에서 감정 상태를 수정할 수 있는지에 대한 issues

**Comment by SangMinYeo** [comment]
사용자의 관점에서 봤을땐 자유도가 높은게 좋다고 봄. 
다만 관련 내용으로 심각한 문제가 발생하고 해결하기 어려운 경우, 수정을 제한할 수 있다고 생각함

**Comment by BaekJinCho** [comment]
- 수정화면이라 사용자에게 최대한 많은 것(감정 상태)을 수정 가능하도록 결정
